# Generated by Django 5.0.7 on 2024-08-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='issue',
            field=models.CharField(choices=[('kpi', 'Impacted KPIs'), ('fas', 'FAS Issue'), ('call_failure', 'Call Failure')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='traffic',
            field=models.CharField(choices=[('incoming', 'Incoming'), ('outcoming', 'Outcoming')], max_length=50),
        ),
    ]
