# Generated by Django 5.0.7 on 2024-08-15 14:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_ticket_id_ticket_ticket_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='issue',
            new_name='category',
        ),
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ticket',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('acknowledged', 'Acknowledged'), ('inprogress', 'In Progress'), ('solved', 'solved')], default='submitted', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='submitted_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
